[PROTOCOLS]
Virtual Screening = [
	{"tag": "section", "text": "Library Filters", "openItem": "False", "children": [
	     {"tag": "protocol", "value": "ProtOmniBindPrediction",   "text": "default"}
	]}
    ]